version: '2.7'
server:
  command: "php public/index.php"
  env:
    - APP_ENV: prod
    - APP_RUNTIME: Runtime\RoadRunnerSymfonyNyholm\Runtime
http:
  address: 0.0.0.0:6000
  middleware: ['static']
  pool:
    num_workers: 4
  static:
    dir: './public'
