version: '3'
server:
  command: "php public/index.php"
  env:
    - APP_ENV: prod
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
http:
  address: 0.0.0.0:6000
  middleware: ['static']
  pool:
    num_workers: 2
    supervisor:
        ttl: 300s
        max_worker_memory: 256
  static:
    dir: './public'
