version: '3.8'
services:
    nginx:
        image: ghcr.io/endroid/docker-nginx:1.1.2
        volumes:
            - .:/var/www/html
            - ~/.letsencrypt:/etc/letsencrypt
        depends_on:
            - node
            - php
        ports:
            - '80:80'
            - '443:443'
            - '9000:9000'
            - '3000:3000'
            - '5000:5000'
            - '8000:8000'

    php:
        image: ghcr.io/endroid/docker-php:1.3.2
        volumes:
            - .:/var/www/html
            - ~/.composer:/home/www-data/.composer
            - ~/.gitconfig:/home/www-data/.gitconfig
            - ~/.gitignore_global:/home/www-data/.gitignore_global
            - ~/.ssh:/home/www-data/.ssh
        depends_on:
            - postgres
            - redis
        expose:
            - 9000
        ports:
            - '6001:6000'

    node:
        image: ghcr.io/endroid/docker-node:1.2.0
        tty: true
        environment:
            NODE_ENV: development
        volumes:
            - .:/app
            - ~/.gitconfig:/home/node/.gitconfig
            - ~/.npm:/home/node/.npm
        depends_on:
            - postgres
            - redis
        ports:
            - '3001:3000'
            - '5173:5173'

    python:
        image: ghcr.io/endroid/docker-python:1.0.4
        tty: true
        volumes:
            - .:/app
            - ~/.gitconfig:/home/python/.gitconfig
        ports:
            - '5001:5000'

    rust:
        image: ghcr.io/endroid/docker-rust:1.0.4
        tty: true
        volumes:
            - .:/app
            - ~/.gitconfig:/home/rust/.gitconfig
        expose:
            - '8001:8000'

    redis:
        image: redis:7.0.5
        volumes:
            - .docker/redis/data:/data
        expose:
            - 6379

    postgres:
        image: postgres:15.1
        environment:
            POSTGRES_DB: nestjs
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - .docker/postgres/data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
