version: '3.8'
services:
    nginx:
        build: .docker/nginx
        volumes:
            - .:/app:rw
        depends_on:
            - node
            - php
        ports:
            - 80:80
            - 443:443
            - 3000:3000
    node:
        image: ghcr.io/endroid/docker-node:1.0.1
        tty: true
        volumes:
            - .:/app:rw
            - ~/.gitconfig:/home/node/.gitconfig
        depends_on:
            - postgres
            - redis
        expose:
            - 3000
    php:
        image: ghcr.io/endroid/docker-php:1.0.6
        environment:
            COMPOSER_AUTH: ~
        volumes:
            - .:/var/www/html
            - ~/.gitconfig:/var/www/.gitconfig
            - ~/.composer:/var/www/.composer
        depends_on:
            - postgres
            - redis
        expose:
            - 9000
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: application
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - .docker/postgres/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    redis:
        image: redis:latest
        volumes:
            - .docker/redis/data:/data
        expose:
            - 6379
    blackfire:
        image: blackfire/blackfire:2
        environment:
            # Do not change: instead set these envs on your host
            BLACKFIRE_SERVER_ID: ~
            BLACKFIRE_SERVER_TOKEN: ~
            BLACKFIRE_CLIENT_ID: ~
            BLACKFIRE_CLIENT_TOKEN: ~
