#!/bin/bash

set -ex

cd "$(dirname "$0")"

rm -rf application

composer create-project symfony/website-skeleton:^6.0 application --no-interaction

(
    cd application

    composer config minimum-stability dev
    composer config prefer-stable true
    composer config extra.symfony.allow-contrib true
    composer config platform.php 8.1

    cp -r ../base/. ./

    # Use source when installing personal libraries
    sed -i -e s#\"[*]\":#\"endroid/*\":\"source\",\"*\":#g composer.json

    composer config repositories.play-bundle vcs git@github.com:endroid/play-bundle.git

    composer require \
        php:^8.1 \
        doctrine/doctrine-fixtures-bundle \
        endroid/asset:dev-master \
        endroid/calendar:dev-master \
        endroid/composer-message:dev-master \
        endroid/data-sanitize:dev-master \
        endroid/data-sanitize-bundle:dev-master \
        endroid/data-sanitize-demo-bundle:dev-master \
        endroid/embed:dev-master \
        endroid/flusher:dev-master \
        endroid/image-placeholder:dev-master \
        endroid/installer:dev-master \
        endroid/play-bundle:dev-master \
        endroid/property-access:dev-master \
        endroid/qr-code:dev-master \
        endroid/qr-code-bundle:dev-master \
        endroid/quality:dev-master \
        endroid/simple-spreadsheet:dev-master \
        endroid/soccer-calendar:dev-master \
        endroid/soccer-calendar-bundle:dev-master \
        endroid/soccer-data:dev-master \
        endroid/sudoku:dev-master \
        endroid/teleporter:dev-master \
        endroid/tile:dev-master \
        predis/predis \
        snc/redis-bundle \
        symfony/messenger:* \
        --update-with-all-dependencies --no-interaction

    bin/console doctrine:database:drop --if-exists --force
    bin/console doctrine:database:create
    bin/console doctrine:migrations:diff

    bin/setup

    git init
    git add -A && git commit -m "Initial commit"
)
