#!/bin/bash

set -ex

cd "$(dirname "$0")"

rm -rf application

nest new application --package-manager npm

(
    cd application
    npm install @nestjs/typeorm typeorm pg typeorm-fixtures-cli
    npm install @nestjs/graphql graphql@^15.0 apollo-server-express
    npm install class-validator class-transformer
    npm install @nestjs/axios @nestjs/config @nestjs/serve-static
    nest info

    cp -r ../base/. ./
    rm -rf **/*.spec.ts
    npm run build

    jq '.compilerOptions.noImplicitAny = true' tsconfig.json | sponge tsconfig.json
    jq '.compilerOptions.strictNullChecks = true' tsconfig.json | sponge tsconfig.json

    npx typeorm schema:drop
    bin/migration/generate

    bin/check
    bin/test

    git init
    git add -A && git commit -m "Initial commit"
)
