#!/bin/bash

set -ex

cd "$(dirname "$0")"

rm -rf application

nest new application --package-manager npm

(
    cd application
    npm install @nestjs/typeorm typeorm pg typeorm-fixtures-cli
    npm install @nestjs/graphql graphql@^15.0 apollo-server-express
    npm install class-validator class-transformer
    npm install @nestjs/axios @nestjs/serve-static
    nest info

    cp -r ../base/. ./
    rm -rf **/*.spec.ts
    npm run build

    npx typeorm schema:drop
    npx typeorm migration:generate -n build
    npm run build

    npx typeorm migration:run
    npx fixtures ./fixtures --config ./ormconfig.json

    git init
    git add -A && git commit -m "Initial commit"
)
