api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    graphql:
        graphql_playground:
            enabled: false